name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build-linux-amd64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config libgtk-3-dev libwebkit2gtk-4.0-dev

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.11.0

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build
        run: wails build -clean -ldflags "-s -w"

      - uses: actions/upload-artifact@v4
        with:
          name: binaries-linux-amd64
          path: build/bin/*


  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.11.0

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build
        run: wails build -clean -ldflags "-s -w"

      - uses: actions/upload-artifact@v4
        with:
          name: binaries-macos
          path: build/bin/*


  build-windows-amd64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.11.0

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build
        run: wails build -clean -nsis -ldflags "-s -w"

      - uses: actions/upload-artifact@v4
        with:
          name: binaries-windows-amd64
          path: build/bin/*


  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux-amd64
      - build-macos
      - build-windows-amd64
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: binaries
          merge-multiple: true

      - uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          generateReleaseNotes: true
          replacesArtifacts: true
          artifacts: binaries/*
